{
  "build": "pyhd8ed1ab_0",
  "build_number": 0,
  "channel": "https://conda.anaconda.org/conda-forge/noarch",
  "constrains": [],
  "depends": [
    "python >=3.7"
  ],
  "extracted_package_dir": "C:\\Users\\akula\\anaconda3\\pkgs\\exceptiongroup-1.2.2-pyhd8ed1ab_0",
  "files": [
    "Lib/site-packages/exceptiongroup-1.2.2.dist-info/INSTALLER",
    "Lib/site-packages/exceptiongroup-1.2.2.dist-info/LICENSE",
    "Lib/site-packages/exceptiongroup-1.2.2.dist-info/METADATA",
    "Lib/site-packages/exceptiongroup-1.2.2.dist-info/RECORD",
    "Lib/site-packages/exceptiongroup-1.2.2.dist-info/REQUESTED",
    "Lib/site-packages/exceptiongroup-1.2.2.dist-info/WHEEL",
    "Lib/site-packages/exceptiongroup-1.2.2.dist-info/direct_url.json",
    "Lib/site-packages/exceptiongroup/__init__.py",
    "Lib/site-packages/exceptiongroup/_catch.py",
    "Lib/site-packages/exceptiongroup/_exceptions.py",
    "Lib/site-packages/exceptiongroup/_formatting.py",
    "Lib/site-packages/exceptiongroup/_suppress.py",
    "Lib/site-packages/exceptiongroup/_version.py",
    "Lib/site-packages/exceptiongroup/py.typed",
    ".nonadmin",
    "Lib/site-packages/exceptiongroup/__pycache__/__init__.cpython-312.pyc",
    "Lib/site-packages/exceptiongroup/__pycache__/_catch.cpython-312.pyc",
    "Lib/site-packages/exceptiongroup/__pycache__/_exceptions.cpython-312.pyc",
    "Lib/site-packages/exceptiongroup/__pycache__/_formatting.cpython-312.pyc",
    "Lib/site-packages/exceptiongroup/__pycache__/_suppress.cpython-312.pyc",
    "Lib/site-packages/exceptiongroup/__pycache__/_version.cpython-312.pyc"
  ],
  "fn": "exceptiongroup-1.2.2-pyhd8ed1ab_0.conda",
  "license": "MIT and PSF-2.0",
  "link": {
    "source": "C:\\Users\\akula\\anaconda3\\pkgs\\exceptiongroup-1.2.2-pyhd8ed1ab_0",
    "type": 1
  },
  "md5": "d02ae936e42063ca46af6cdad2dbd1e0",
  "name": "exceptiongroup",
  "noarch": "python",
  "package_tarball_full_path": "C:\\Users\\akula\\anaconda3\\pkgs\\exceptiongroup-1.2.2-pyhd8ed1ab_0.conda",
  "package_type": "noarch_python",
  "paths_data": {
    "paths": [
      {
        "_path": "Lib/site-packages/exceptiongroup/__pycache__/__init__.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/exceptiongroup/__pycache__/_catch.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/exceptiongroup/__pycache__/_exceptions.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/exceptiongroup/__pycache__/_formatting.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/exceptiongroup/__pycache__/_suppress.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/exceptiongroup/__pycache__/_version.cpython-312.pyc",
        "path_type": "pyc_file"
      }
    ],
    "paths_version": 1
  },
  "requested_spec": "None",
  "sha256": "e0edd30c4b7144406bb4da975e6bb97d6bc9c0e999aa4efe66ae108cada5d5b5",
  "size": 20418,
  "subdir": "noarch",
  "timestamp": 1720869435000,
  "url": "https://conda.anaconda.org/conda-forge/noarch/exceptiongroup-1.2.2-pyhd8ed1ab_0.conda",
  "version": "1.2.2"
}